using DnDGen.EventGen;
using DnDGen.TreasureGen.Items;
using DnDGen.TreasureGen.Items.Magical;
using DnDGen.TreasureGen.Tests.Unit.Generators.Items;
using Ninject;
using NUnit.Framework;
using System;

namespace DnDGen.TreasureGen.Tests.Integration.Generators.Items.Magical
{
    [TestFixture]
    public class RingGeneratorTests : IntegrationTests
    {
        [Inject, Named(ItemTypeConstants.Ring)]
        public MagicalItemGenerator RingGenerator { get; set; }
        [Inject]
        public ClientIDManager ClientIDManager { get; set; }

        private ItemVerifier itemVerifier;

        [SetUp]
        public void Setup()
        {
            itemVerifier = new ItemVerifier();
            ClientIDManager.SetClientID(Guid.NewGuid());
        }

        [TestCase(RingConstants.AcidResistance_Greater, PowerConstants.Minor)]
        [TestCase(RingConstants.AcidResistance_Greater, PowerConstants.Medium)]
        [TestCase(RingConstants.AcidResistance_Greater, PowerConstants.Major)]
        [TestCase(RingConstants.AcidResistance_Major, PowerConstants.Minor)]
        [TestCase(RingConstants.AcidResistance_Major, PowerConstants.Medium)]
        [TestCase(RingConstants.AcidResistance_Major, PowerConstants.Major)]
        [TestCase(RingConstants.AcidResistance_Minor, PowerConstants.Minor)]
        [TestCase(RingConstants.AcidResistance_Minor, PowerConstants.Medium)]
        [TestCase(RingConstants.AcidResistance_Minor, PowerConstants.Major)]
        [TestCase(RingConstants.AnimalFriendship, PowerConstants.Minor)]
        [TestCase(RingConstants.AnimalFriendship, PowerConstants.Medium)]
        [TestCase(RingConstants.AnimalFriendship, PowerConstants.Major)]
        [TestCase(RingConstants.Blinking, PowerConstants.Minor)]
        [TestCase(RingConstants.Blinking, PowerConstants.Medium)]
        [TestCase(RingConstants.Blinking, PowerConstants.Major)]
        [TestCase(RingConstants.ChameleonPower, PowerConstants.Minor)]
        [TestCase(RingConstants.ChameleonPower, PowerConstants.Medium)]
        [TestCase(RingConstants.ChameleonPower, PowerConstants.Major)]
        [TestCase(RingConstants.Climbing, PowerConstants.Minor)]
        [TestCase(RingConstants.Climbing, PowerConstants.Medium)]
        [TestCase(RingConstants.Climbing, PowerConstants.Major)]
        [TestCase(RingConstants.Climbing_Improved, PowerConstants.Minor)]
        [TestCase(RingConstants.Climbing_Improved, PowerConstants.Medium)]
        [TestCase(RingConstants.Climbing_Improved, PowerConstants.Major)]
        [TestCase(RingConstants.Clumsiness, PowerConstants.Minor)]
        [TestCase(RingConstants.Clumsiness, PowerConstants.Medium)]
        [TestCase(RingConstants.Clumsiness, PowerConstants.Major)]
        [TestCase(RingConstants.ColdResistance_Greater, PowerConstants.Minor)]
        [TestCase(RingConstants.ColdResistance_Greater, PowerConstants.Medium)]
        [TestCase(RingConstants.ColdResistance_Greater, PowerConstants.Major)]
        [TestCase(RingConstants.ColdResistance_Major, PowerConstants.Minor)]
        [TestCase(RingConstants.ColdResistance_Major, PowerConstants.Medium)]
        [TestCase(RingConstants.ColdResistance_Major, PowerConstants.Major)]
        [TestCase(RingConstants.ColdResistance_Minor, PowerConstants.Minor)]
        [TestCase(RingConstants.ColdResistance_Minor, PowerConstants.Medium)]
        [TestCase(RingConstants.ColdResistance_Minor, PowerConstants.Major)]
        [TestCase(RingConstants.Counterspells, PowerConstants.Minor)]
        [TestCase(RingConstants.Counterspells, PowerConstants.Medium)]
        [TestCase(RingConstants.Counterspells, PowerConstants.Major)]
        [TestCase(RingConstants.DjinniCalling, PowerConstants.Minor)]
        [TestCase(RingConstants.DjinniCalling, PowerConstants.Medium)]
        [TestCase(RingConstants.DjinniCalling, PowerConstants.Major)]
        [TestCase(RingConstants.ElectricityResistance_Greater, PowerConstants.Minor)]
        [TestCase(RingConstants.ElectricityResistance_Greater, PowerConstants.Medium)]
        [TestCase(RingConstants.ElectricityResistance_Greater, PowerConstants.Major)]
        [TestCase(RingConstants.ElectricityResistance_Major, PowerConstants.Minor)]
        [TestCase(RingConstants.ElectricityResistance_Major, PowerConstants.Medium)]
        [TestCase(RingConstants.ElectricityResistance_Major, PowerConstants.Major)]
        [TestCase(RingConstants.ElectricityResistance_Minor, PowerConstants.Minor)]
        [TestCase(RingConstants.ElectricityResistance_Minor, PowerConstants.Medium)]
        [TestCase(RingConstants.ElectricityResistance_Minor, PowerConstants.Major)]
        [TestCase(RingConstants.ElementalCommand_Air, PowerConstants.Minor)]
        [TestCase(RingConstants.ElementalCommand_Air, PowerConstants.Medium)]
        [TestCase(RingConstants.ElementalCommand_Air, PowerConstants.Major)]
        [TestCase(RingConstants.ElementalCommand_Earth, PowerConstants.Minor)]
        [TestCase(RingConstants.ElementalCommand_Earth, PowerConstants.Medium)]
        [TestCase(RingConstants.ElementalCommand_Earth, PowerConstants.Major)]
        [TestCase(RingConstants.ElementalCommand_Fire, PowerConstants.Minor)]
        [TestCase(RingConstants.ElementalCommand_Fire, PowerConstants.Medium)]
        [TestCase(RingConstants.ElementalCommand_Fire, PowerConstants.Major)]
        [TestCase(RingConstants.ElementalCommand_Water, PowerConstants.Minor)]
        [TestCase(RingConstants.ElementalCommand_Water, PowerConstants.Medium)]
        [TestCase(RingConstants.ElementalCommand_Water, PowerConstants.Major)]
        [TestCase(RingConstants.ENERGYResistance_Greater, PowerConstants.Minor)]
        [TestCase(RingConstants.ENERGYResistance_Greater, PowerConstants.Medium)]
        [TestCase(RingConstants.ENERGYResistance_Greater, PowerConstants.Major)]
        [TestCase(RingConstants.ENERGYResistance_Major, PowerConstants.Minor)]
        [TestCase(RingConstants.ENERGYResistance_Major, PowerConstants.Medium)]
        [TestCase(RingConstants.ENERGYResistance_Major, PowerConstants.Major)]
        [TestCase(RingConstants.ENERGYResistance_Minor, PowerConstants.Minor)]
        [TestCase(RingConstants.ENERGYResistance_Minor, PowerConstants.Medium)]
        [TestCase(RingConstants.ENERGYResistance_Minor, PowerConstants.Major)]
        [TestCase(RingConstants.FeatherFalling, PowerConstants.Minor)]
        [TestCase(RingConstants.FeatherFalling, PowerConstants.Medium)]
        [TestCase(RingConstants.FeatherFalling, PowerConstants.Major)]
        [TestCase(RingConstants.FireResistance_Greater, PowerConstants.Minor)]
        [TestCase(RingConstants.FireResistance_Greater, PowerConstants.Medium)]
        [TestCase(RingConstants.FireResistance_Greater, PowerConstants.Major)]
        [TestCase(RingConstants.FireResistance_Major, PowerConstants.Minor)]
        [TestCase(RingConstants.FireResistance_Major, PowerConstants.Medium)]
        [TestCase(RingConstants.FireResistance_Major, PowerConstants.Major)]
        [TestCase(RingConstants.FireResistance_Minor, PowerConstants.Minor)]
        [TestCase(RingConstants.FireResistance_Minor, PowerConstants.Medium)]
        [TestCase(RingConstants.FireResistance_Minor, PowerConstants.Major)]
        [TestCase(RingConstants.ForceShield, PowerConstants.Minor)]
        [TestCase(RingConstants.ForceShield, PowerConstants.Medium)]
        [TestCase(RingConstants.ForceShield, PowerConstants.Major)]
        [TestCase(RingConstants.FreedomOfMovement, PowerConstants.Minor)]
        [TestCase(RingConstants.FreedomOfMovement, PowerConstants.Medium)]
        [TestCase(RingConstants.FreedomOfMovement, PowerConstants.Major)]
        [TestCase(RingConstants.FriendShield, PowerConstants.Minor)]
        [TestCase(RingConstants.FriendShield, PowerConstants.Medium)]
        [TestCase(RingConstants.FriendShield, PowerConstants.Major)]
        [TestCase(RingConstants.Invisibility, PowerConstants.Minor)]
        [TestCase(RingConstants.Invisibility, PowerConstants.Medium)]
        [TestCase(RingConstants.Invisibility, PowerConstants.Major)]
        [TestCase(RingConstants.Jumping, PowerConstants.Minor)]
        [TestCase(RingConstants.Jumping, PowerConstants.Medium)]
        [TestCase(RingConstants.Jumping, PowerConstants.Major)]
        [TestCase(RingConstants.Jumping_Improved, PowerConstants.Minor)]
        [TestCase(RingConstants.Jumping_Improved, PowerConstants.Medium)]
        [TestCase(RingConstants.Jumping_Improved, PowerConstants.Major)]
        [TestCase(RingConstants.MindShielding, PowerConstants.Minor)]
        [TestCase(RingConstants.MindShielding, PowerConstants.Medium)]
        [TestCase(RingConstants.MindShielding, PowerConstants.Major)]
        [TestCase(RingConstants.Protection, PowerConstants.Minor)]
        [TestCase(RingConstants.Protection, PowerConstants.Medium)]
        [TestCase(RingConstants.Protection, PowerConstants.Major)]
        [TestCase(RingConstants.Ram, PowerConstants.Minor)]
        [TestCase(RingConstants.Ram, PowerConstants.Medium)]
        [TestCase(RingConstants.Ram, PowerConstants.Major)]
        [TestCase(RingConstants.Regeneration, PowerConstants.Minor)]
        [TestCase(RingConstants.Regeneration, PowerConstants.Medium)]
        [TestCase(RingConstants.Regeneration, PowerConstants.Major)]
        [TestCase(RingConstants.ShootingStars, PowerConstants.Minor)]
        [TestCase(RingConstants.ShootingStars, PowerConstants.Medium)]
        [TestCase(RingConstants.ShootingStars, PowerConstants.Major)]
        [TestCase(RingConstants.SonicResistance_Greater, PowerConstants.Minor)]
        [TestCase(RingConstants.SonicResistance_Greater, PowerConstants.Medium)]
        [TestCase(RingConstants.SonicResistance_Greater, PowerConstants.Major)]
        [TestCase(RingConstants.SonicResistance_Major, PowerConstants.Minor)]
        [TestCase(RingConstants.SonicResistance_Major, PowerConstants.Medium)]
        [TestCase(RingConstants.SonicResistance_Major, PowerConstants.Major)]
        [TestCase(RingConstants.SonicResistance_Minor, PowerConstants.Minor)]
        [TestCase(RingConstants.SonicResistance_Minor, PowerConstants.Medium)]
        [TestCase(RingConstants.SonicResistance_Minor, PowerConstants.Major)]
        [TestCase(RingConstants.SpellStoring, PowerConstants.Minor)]
        [TestCase(RingConstants.SpellStoring, PowerConstants.Medium)]
        [TestCase(RingConstants.SpellStoring, PowerConstants.Major)]
        [TestCase(RingConstants.SpellStoring_Major, PowerConstants.Minor)]
        [TestCase(RingConstants.SpellStoring_Major, PowerConstants.Medium)]
        [TestCase(RingConstants.SpellStoring_Major, PowerConstants.Major)]
        [TestCase(RingConstants.SpellStoring_Minor, PowerConstants.Minor)]
        [TestCase(RingConstants.SpellStoring_Minor, PowerConstants.Medium)]
        [TestCase(RingConstants.SpellStoring_Minor, PowerConstants.Major)]
        [TestCase(RingConstants.SpellTurning, PowerConstants.Minor)]
        [TestCase(RingConstants.SpellTurning, PowerConstants.Medium)]
        [TestCase(RingConstants.SpellTurning, PowerConstants.Major)]
        [TestCase(RingConstants.Sustenance, PowerConstants.Minor)]
        [TestCase(RingConstants.Sustenance, PowerConstants.Medium)]
        [TestCase(RingConstants.Sustenance, PowerConstants.Major)]
        [TestCase(RingConstants.Swimming, PowerConstants.Minor)]
        [TestCase(RingConstants.Swimming, PowerConstants.Medium)]
        [TestCase(RingConstants.Swimming, PowerConstants.Major)]
        [TestCase(RingConstants.Swimming_Improved, PowerConstants.Minor)]
        [TestCase(RingConstants.Swimming_Improved, PowerConstants.Medium)]
        [TestCase(RingConstants.Swimming_Improved, PowerConstants.Major)]
        [TestCase(RingConstants.Telekinesis, PowerConstants.Minor)]
        [TestCase(RingConstants.Telekinesis, PowerConstants.Medium)]
        [TestCase(RingConstants.Telekinesis, PowerConstants.Major)]
        [TestCase(RingConstants.ThreeWishes, PowerConstants.Minor)]
        [TestCase(RingConstants.ThreeWishes, PowerConstants.Medium)]
        [TestCase(RingConstants.ThreeWishes, PowerConstants.Major)]
        [TestCase(RingConstants.WaterWalking, PowerConstants.Minor)]
        [TestCase(RingConstants.WaterWalking, PowerConstants.Medium)]
        [TestCase(RingConstants.WaterWalking, PowerConstants.Major)]
        [TestCase(RingConstants.Wizardry_I, PowerConstants.Minor)]
        [TestCase(RingConstants.Wizardry_I, PowerConstants.Medium)]
        [TestCase(RingConstants.Wizardry_I, PowerConstants.Major)]
        [TestCase(RingConstants.Wizardry_II, PowerConstants.Minor)]
        [TestCase(RingConstants.Wizardry_II, PowerConstants.Medium)]
        [TestCase(RingConstants.Wizardry_II, PowerConstants.Major)]
        [TestCase(RingConstants.Wizardry_III, PowerConstants.Minor)]
        [TestCase(RingConstants.Wizardry_III, PowerConstants.Medium)]
        [TestCase(RingConstants.Wizardry_III, PowerConstants.Major)]
        [TestCase(RingConstants.Wizardry_IV, PowerConstants.Minor)]
        [TestCase(RingConstants.Wizardry_IV, PowerConstants.Medium)]
        [TestCase(RingConstants.Wizardry_IV, PowerConstants.Major)]
        [TestCase(RingConstants.XRayVision, PowerConstants.Minor)]
        [TestCase(RingConstants.XRayVision, PowerConstants.Medium)]
        [TestCase(RingConstants.XRayVision, PowerConstants.Major)]
        public void GenerateRing(string itemName, string power)
        {
            var isOfPower = RingGenerator.IsItemOfPower(itemName, power);
            Assert.That(isOfPower, Is.True);

            var item = RingGenerator.GenerateFrom(power, itemName);
            itemVerifier.AssertItem(item);
        }
    }
}
