using DnDGen.EventGen;
using DnDGen.TreasureGen.Items;
using DnDGen.TreasureGen.Items.Magical;
using DnDGen.TreasureGen.Tests.Unit.Generators.Items;
using Ninject;
using NUnit.Framework;
using System;

namespace DnDGen.TreasureGen.Tests.Integration.Generators.Items.Magical
{
    [TestFixture]
    public class WondrousItemGeneratorTests : IntegrationTests
    {
        [Inject, Named(ItemTypeConstants.WondrousItem)]
        public MagicalItemGenerator WondrousItemGenerator { get; set; }
        [Inject]
        public ClientIDManager ClientIDManager { get; set; }

        private ItemVerifier itemVerifier;

        [SetUp]
        public void Setup()
        {
            itemVerifier = new ItemVerifier();
            ClientIDManager.SetClientID(Guid.NewGuid());
        }

        [TestCase(WondrousItemConstants.AmuletOfHealth, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.AmuletOfHealth, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.AmuletOfHealth, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.AmuletOfInescapableLocation, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.AmuletOfInescapableLocation, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.AmuletOfInescapableLocation, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.AmuletOfMightyFists, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.AmuletOfMightyFists, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.AmuletOfMightyFists, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.AmuletOfNaturalArmor, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.AmuletOfNaturalArmor, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.AmuletOfNaturalArmor, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.AmuletOfProofAgainstDetectionAndLocation, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.AmuletOfThePlanes, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.ApparatusOfKwalish, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.BagOfDevouring, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.BagOfDevouring, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.BagOfDevouring, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.BagOfHolding_I, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.BagOfHolding_II, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.BagOfHolding_III, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.BagOfHolding_IV, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.BagOfTricks_Gray, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.BagOfTricks_Rust, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.BagOfTricks_Tan, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.BeadOfForce, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.BeltOfDwarvenkind, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.BeltOfGiantStrength, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.BeltOfGiantStrength, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.BoccobsBlessedBook, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.BootsOfDancing, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.BootsOfDancing, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.BootsOfDancing, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.BootsOfElvenkind, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.BootsOfLevitation, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.BootsOfSpeed, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.BootsOfStridingAndSpringing, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.BootsOfTeleportation, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.BootsOfTheWinterlands, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.BottleOfAir, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.BowlOfCommandingWaterElementals, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.BraceletOfFriends, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.BracersOfArchery_Greater, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.BracersOfArchery_Lesser, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.BracersOfArmor, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.BracersOfArmor, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.BracersOfArmor, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.BracersOfDefenselessness, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.BracersOfDefenselessness, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.BracersOfDefenselessness, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.BrazierOfCommandingFireElementals, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.BroochOfShielding, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.BroomOfAnimatedAttack, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.BroomOfAnimatedAttack, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.BroomOfAnimatedAttack, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.BroomOfFlying, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.CandleOfInvocation, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.CandleOfTruth, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.CapeOfTheMountebank, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.CarpetOfFlying_10x10, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.CarpetOfFlying_5x10, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.CarpetOfFlying_5x5, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.CarpetOfFlying_6x9, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.CenserOfControllingAirElementals, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.ChaosDiamond, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.ChimeOfInterruption, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.ChimeOfOpening, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.CircletOfBlasting_Major, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.CircletOfBlasting_Minor, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.CircletOfPersuasion, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.CloakOfArachnida, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.CloakOfCharisma, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.CloakOfCharisma, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.CloakOfCharisma, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.CloakOfDisplacement_Major, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.CloakOfDisplacement_Minor, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.CloakOfElvenkind, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.CloakOfEtherealness, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.CloakOfPoisonousness, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.CloakOfPoisonousness, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.CloakOfPoisonousness, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.CloakOfResistance, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.CloakOfResistance, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.CloakOfTheBat, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.CloakOfTheMantaRay, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.CrystalBall, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.CrystalBall_DetectThoughts, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.CrystalBall_Hypnosis, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.CrystalBall_Hypnosis, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.CrystalBall_Hypnosis, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.CrystalBall_SeeInvisibility, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.CrystalBall_Telepathy, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.CrystalBall_TrueSeeing, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.CubeOfForce, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.CubeOfFrostResistance, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.CubicGate, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.DaernsInstantFortress, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.Darkskull, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.DecanterOfEndlessWater, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.DeckOfIllusions, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.DeckOfIllusions_Full, PowerConstants.Medium, Ignore = "This is just an internal construct")]
        [TestCase(WondrousItemConstants.DimensionalShackles, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.DruidsVestments, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.DrumsOfPanic, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.DustOfAppearance, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.DustOfDisappearance, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.DustOfDryness, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.DustOfIllusion, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.DustOfSneezingAndChoking, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.DustOfSneezingAndChoking, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.DustOfSneezingAndChoking, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.DustOfTracelessness, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.EfreetiBottle, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.ElementalGem, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.ElixerOfFireBreath, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.ElixerOfHiding, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.ElixerOfLove, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.ElixerOfSneaking, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.ElixerOfSwimming, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.ElixerOfTruth, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.ElixerOfVision, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.EversmokingBottle, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.EyesOfCharming, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.EyesOfDoom, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.EyesOfPetrification, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.EyesOfTheEagle, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.FigurineOfWondrousPower_BronzeGriffon, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.FigurineOfWondrousPower_EbonyFly, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.FigurineOfWondrousPower_GoldenLions, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.FigurineOfWondrousPower_IvoryGoats, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.FigurineOfWondrousPower_MarbleElephant, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.FigurineOfWondrousPower_ObsidianSteed, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.FigurineOfWondrousPower_OnyxDog, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.FigurineOfWondrousPower_SerpentineOwl, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.FigurineOfWondrousPower_SilverRaven, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.FlaskOfCurses, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.FlaskOfCurses, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.FlaskOfCurses, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.FoldingBoat, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.GauntletOfRust, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.GauntletsOfFumbling, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.GauntletsOfFumbling, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.GauntletsOfFumbling, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.GauntletsOfOgrePower, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.GemOfBrightness, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.GemOfSeeing, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.GloveOfStoring, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.GlovesOfArrowSnaring, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.GlovesOfDexterity, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.GlovesOfDexterity, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.GlovesOfDexterity, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.GlovesOfSwimmingAndClimbing, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.GogglesOfMinuteSeeing, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.GogglesOfNight, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.GolembaneScarab, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.GolemManual_Clay, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.GolemManual_Flesh, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.GolemManual_Iron, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.GolemManual_Stone, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.GolemManual_Stone_Greater, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.HandOfGlory, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.HandOfTheMage, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.HarpOfCharming, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.HatOfDisguise, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.HeadbandOfIntellect, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.HeadbandOfIntellect, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.HeadbandOfIntellect, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.HelmOfBrilliance, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.HelmOfComprehendLanguagesAndReadMagic, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.HelmOfOppositeAlignment, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.HelmOfOppositeAlignment, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.HelmOfOppositeAlignment, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.HelmOfTelepathy, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.HelmOfTeleportation, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.HelmOfUnderwaterAction, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.HewardsHandyHaversack, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.HornOfBlasting, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.HornOfBlasting_Greater, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.HornOfFog, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.HornOfGoodnessEvil, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.HornOfTheTritons, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.HornOfValhalla, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.HorseshoesOfAZephyr, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.HorseshoesOfSpeed, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.IncenseOfMeditation, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.IncenseOfObsession, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.IncenseOfObsession, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.IncenseOfObsession, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.IounStone_ClearSpindle, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.IounStone_DarkBlueRhomboid, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.IounStone_DeepRedSphere, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.IounStone_DustyRosePrism, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.IounStone_IncandescentBlueSphere, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.IounStone_IridescentSpindle, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.IounStone_LavenderAndGreenEllipsoid, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.IounStone_OrangePrism, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.IounStone_PaleBlueRhomboid, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.IounStone_PaleGreenPrism, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.IounStone_PaleLavenderEllipsoid, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.IounStone_PearlyWhiteSpindle, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.IounStone_PinkAndGreenSphere, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.IounStone_PinkRhomboid, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.IounStone_ScarletAndBlueSphere, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.IounStone_VibrantPurplePrism, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.IronBandsOfBilarro, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.IronFlask, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.KeoghtomsOintment, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.LanternOfRevealing, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.LensOfDetection, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.LyreOfBuilding, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.MantleOfFaith, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.MantleOfSpellResistance, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.ManualOfBodilyHealth, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.ManualOfBodilyHealth, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.ManualOfGainfulExercise, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.ManualOfGainfulExercise, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.ManualOfQuicknessInAction, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.ManualOfQuicknessInAction, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.MaskOfTheSkull, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.MattockOfTheTitans, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.MaulOfTheTitans, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.MedallionOfThoughtProjection, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.MedallionOfThoughtProjection, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.MedallionOfThoughtProjection, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.MedallionOfThoughts, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.MirrorOfLifeTrapping, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.MirrorOfMentalProwess, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.MirrorOfOpposition, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.MonksBelt, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.MurlyndsSpoon, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.NecklaceOfAdaptation, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.NecklaceOfFireballs, PowerConstants.Minor, Ignore = "This is just an internal construct")]
        [TestCase(WondrousItemConstants.NecklaceOfFireballs, PowerConstants.Medium, Ignore = "This is just an internal construct")]
        [TestCase(WondrousItemConstants.NecklaceOfFireballs_I, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.NecklaceOfFireballs_II, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.NecklaceOfFireballs_III, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.NecklaceOfFireballs_IV, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.NecklaceOfFireballs_V, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.NecklaceOfFireballs_VI, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.NecklaceOfFireballs_VII, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.NecklaceOfStrangulation, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.NecklaceOfStrangulation, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.NecklaceOfStrangulation, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.NolzursMarvelousPigments, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.OrbOfStorms, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.PearlOfPower_1stLevel, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.PearlOfPower_2ndLevel, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.PearlOfPower_3rdLevel, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.PearlOfPower_4thLevel, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.PearlOfPower_5thLevel, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.PearlOfPower_6thLevel, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.PearlOfPower_7thLevel, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.PearlOfPower_8thLevel, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.PearlOfPower_9thLevel, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.PearlOfPower_TwoSpells, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.PearlOfTheSirines, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.PeriaptOfFoulRotting, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.PeriaptOfFoulRotting, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.PeriaptOfFoulRotting, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.PeriaptOfHealth, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.PeriaptOfProofAgainstPoison, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.PeriaptOfWisdom, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.PeriaptOfWisdom, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.PeriaptOfWisdom, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.PeriaptOfWoundClosure, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.PhylacteryOfFaithfulness, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.PhylacteryOfUndeadTurning, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.PipesOfHaunting, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.PipesOfPain, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.PipesOfSounding, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.PipesOfTheSewers, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.PortableHole, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.QuaalsFeatherToken_Anchor, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.QuaalsFeatherToken_Bird, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.QuaalsFeatherToken_Fan, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.QuaalsFeatherToken_SwanBoat, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.QuaalsFeatherToken_Tree, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.QuaalsFeatherToken_Whip, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.QuiverOfEhlonna, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.RingGates, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.RobeOfBlending, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.RobeOfBones, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.RobeOfEyes, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.RobeOfPowerlessness, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.RobeOfPowerlessness, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.RobeOfPowerlessness, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.RobeOfScintillatingColors, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.RobeOfStars, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.RobeOfTheArchmagi, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.RobeOfUsefulItems, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.RobeOfVermin, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.RobeOfVermin, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.RobeOfVermin, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.RopeOfClimbing, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.RopeOfEntanglement, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.SalveOfSlipperiness, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.ScabbardOfKeenEdges, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.ScarabOfDeath, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.ScarabOfDeath, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.ScarabOfDeath, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.ScarabOfProtection, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.Silversheen, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.SlippersOfSpiderClimbing, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.SovereignGlue, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.StoneHorse_Courser, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.StoneHorse_Destrier, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.StoneOfAlarm, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.StoneOfControllingEarthElementals, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.StoneOfGoodLuck_Luckstone, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.StoneOfWeight_Loadstone, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.StoneOfWeight_Loadstone, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.StoneOfWeight_Loadstone, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.StoneSalve, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.StrandOfPrayerBeads, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.StrandOfPrayerBeads_Greater, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.StrandOfPrayerBeads_Lesser, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.TalismanOfTheSphere, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.TomeOfClearThought, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.TomeOfClearThought, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.TomeOfLeadershipAndInfluence, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.TomeOfLeadershipAndInfluence, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.TomeOfUnderstanding, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.TomeOfUnderstanding, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.UnguentOfTimelessness, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.UniversalSolvent, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.VacousGrimoire, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.VacousGrimoire, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.VacousGrimoire, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.VestOfEscape, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.WellOfManyWorlds, PowerConstants.Major)]
        [TestCase(WondrousItemConstants.WindFan, PowerConstants.Minor)]
        [TestCase(WondrousItemConstants.WingedBoots, PowerConstants.Medium)]
        [TestCase(WondrousItemConstants.WingsOfFlying, PowerConstants.Major)]
        public void GenerateWondrousItem(string itemName, string power)
        {
            var isOfPower = WondrousItemGenerator.IsItemOfPower(itemName, power);
            Assert.That(isOfPower, Is.True);

            var item = WondrousItemGenerator.Generate(power, itemName);
            itemVerifier.AssertItem(item);
        }

        [Test]
        public void AllWondrousItemsCanBeGenerated()
        {
            var wondrousItems = WondrousItemConstants.GetAllWondrousItems();

            foreach (var wondrousItem in wondrousItems)
            {
                var isMinor = WondrousItemGenerator.IsItemOfPower(wondrousItem, PowerConstants.Minor);
                var isMedium = WondrousItemGenerator.IsItemOfPower(wondrousItem, PowerConstants.Medium);
                var isMajor = WondrousItemGenerator.IsItemOfPower(wondrousItem, PowerConstants.Major);

                Assert.That(true, Is.EqualTo(isMinor)
                    .Or.EqualTo(isMedium)
                    .Or.EqualTo(isMajor), wondrousItem);
            }
        }
    }
}
