using NUnit.Framework;
using System;
using TreasureGen.Items.Magical;

namespace TreasureGen.Tests.Unit.Generators.Items.Magical
{
    [TestFixture]
    public class PotionConstantsTests
    {
        [TestCase(PotionConstants.Aid, "Potion of aid")]
        [TestCase(PotionConstants.Barkskin, "Potion of barkskin")]
        [TestCase(PotionConstants.BearsEndurance, "Potion of bear's endurance")]
        [TestCase(PotionConstants.BlessWeapon, "Oil of bless weapon")]
        [TestCase(PotionConstants.Blur, "Potion of blur")]
        [TestCase(PotionConstants.BullsStrength, "Potion of bull's strength")]
        [TestCase(PotionConstants.CatsGrace, "Potion of cat's grace")]
        [TestCase(PotionConstants.CureLightWounds, "Potion of cure light wounds")]
        [TestCase(PotionConstants.CureModerateWounds, "Potion of cure moderate wounds")]
        [TestCase(PotionConstants.CureSeriousWounds, "Potion of cure serious wounds")]
        [TestCase(PotionConstants.Darkness, "Oil of darkness")]
        [TestCase(PotionConstants.Darkvision, "Potion of darkvision")]
        [TestCase(PotionConstants.Daylight, "Oil of daylight")]
        [TestCase(PotionConstants.DelayPoison, "Potion of delay poison")]
        [TestCase(PotionConstants.Displacement, "Potion of displacement")]
        [TestCase(PotionConstants.EaglesSplendor, "Potion of eagle's splendor")]
        [TestCase(PotionConstants.EndureElements, "Potion of endure elements")]
        [TestCase(PotionConstants.EnlargePerson, "Potion of enlarge person")]
        [TestCase(PotionConstants.FlameArrow, "Oil of flame arrow")]
        [TestCase(PotionConstants.Fly, "Potion of fly")]
        [TestCase(PotionConstants.FoxsCunning, "Potion of fox's cunning")]
        [TestCase(PotionConstants.GaseousForm, "Potion of gaseous form")]
        [TestCase(PotionConstants.GoodHope, "Potion of good hope")]
        [TestCase(PotionConstants.Haste, "Potion of haste")]
        [TestCase(PotionConstants.Heroism, "Potion of heroism")]
        [TestCase(PotionConstants.HideFromAnimals, "Potion of hide from animals")]
        [TestCase(PotionConstants.HideFromUndead, "Potion of hide from undead")]
        [TestCase(PotionConstants.Invisibility_Oil, "Oil of invisibility")]
        [TestCase(PotionConstants.Invisibility_Potion, "Potion of invisibility")]
        [TestCase(PotionConstants.Jump, "Potion of jump")]
        [TestCase(PotionConstants.KeenEdge, "Oil of keen edge")]
        [TestCase(PotionConstants.Levitate_Oil, "Oil of levitate")]
        [TestCase(PotionConstants.Levitate_Potion, "Potion of levitate")]
        [TestCase(PotionConstants.MageArmor, "Potion of mage armor")]
        [TestCase(PotionConstants.MagicCircleAgainstPARTIALALIGNMENT, "Potion of magic circle against PARTIALALIGNMENT")]
        [TestCase(PotionConstants.MagicFang, "Potion of magic fang")]
        [TestCase(PotionConstants.MagicFang_Greater, "Potion of greater magic fang")]
        [TestCase(PotionConstants.MagicStone, "Oil of magic stone")]
        [TestCase(PotionConstants.MagicVestment, "Oil of magic vestment")]
        [TestCase(PotionConstants.MagicWeapon, "Oil of magic weapon")]
        [TestCase(PotionConstants.MagicWeapon_Greater, "Oil of greater magic weapon")]
        [TestCase(PotionConstants.Misdirection, "Potion of misdirection")]
        [TestCase(PotionConstants.NeutralizePoison, "Potion of neutralize poison")]
        [TestCase(PotionConstants.Nondetection, "Potion of nondetection")]
        [TestCase(PotionConstants.OwlsWisdom, "Potion of owl's wisdom")]
        [TestCase(PotionConstants.PassWithoutTrace, "Potion of pass without trace")]
        [TestCase(PotionConstants.Poison, "Potion of poison")]
        [TestCase(PotionConstants.ProtectionFromPARTIALALIGNMENT, "Potion of protection from PARTIALALIGNMENT")]
        [TestCase(PotionConstants.ProtectionFromArrows_10, "Potion of protection from arrows 10/magic")]
        [TestCase(PotionConstants.ProtectionFromArrows_15, "Potion of protection from arrows 15/magic")]
        [TestCase(PotionConstants.ProtectionFromENERGY, "Potion of protection from ENERGY")]
        [TestCase(PotionConstants.Rage, "Potion of rage")]
        [TestCase(PotionConstants.RemoveBlindnessDeafness, "Potion of remove blindness/deafness")]
        [TestCase(PotionConstants.RemoveCurse, "Potion of remove curse")]
        [TestCase(PotionConstants.RemoveDisease, "Potion of remove disease")]
        [TestCase(PotionConstants.ReducePerson, "Potion of reduce person")]
        [TestCase(PotionConstants.RemoveFear, "Potion of remove fear")]
        [TestCase(PotionConstants.RemoveParalysis, "Potion of remove paralysis")]
        [TestCase(PotionConstants.ResistENERGY_10, "Potion of resist ENERGY 10")]
        [TestCase(PotionConstants.ResistENERGY_20, "Potion of resist ENERGY 20")]
        [TestCase(PotionConstants.ResistENERGY_30, "Potion of resist ENERGY 30")]
        [TestCase(PotionConstants.Restoration_Lesser, "Potion of lesser restoration")]
        [TestCase(PotionConstants.Sanctuary, "Potion of sanctuary")]
        [TestCase(PotionConstants.ShieldOfFaith, "Potion of shield of faith")]
        [TestCase(PotionConstants.Shillelagh, "Oil of shillelagh")]
        [TestCase(PotionConstants.SpiderClimb, "Potion of spider climb")]
        [TestCase(PotionConstants.Tongues, "Potion of tongues")]
        [TestCase(PotionConstants.UndetectableAlignment, "Potion of undetectable alignment")]
        [TestCase(PotionConstants.WaterBreathing, "Potion of water breathing")]
        [TestCase(PotionConstants.WaterWalk, "Potion of water walk")]
        public void Constant(String constant, String value)
        {
            Assert.That(constant, Is.EqualTo(value));
        }
    }
}