using System;

namespace EquipmentGen.Core.Data.Items.Constants
{
    public static class WeaponConstants
    {
        public const String Dagger = "Dagger";
        public const String Greataxe = "Greataxe";
        public const String Greatsword = "Greatsword";
        public const String Kama = "Kama";
        public const String Longsword = "Longsword";
        public const String LightMace = "Light mace";
        public const String HeavyMace = "Heavy mace";
        public const String Nunchaku = "Nunchaku";
        public const String Quarterstaff = "Quarterstaff";
        public const String Rapier = "Rapier";
        public const String Scimitar = "Scimitar";
        public const String Shortspear = "Shortspear";
        public const String Siangham = "Siangham";
        public const String BastardSword = "Bastard sword";
        public const String ShortSword = "Short sword";
        public const String DwarvenWaraxe = "Dwarven waraxe";
        public const String OrcDoubleAxe = "Orc double axe";
        public const String Battleaxe = "Battleaxe";
        public const String SpikedChain = "Spiked chain";
        public const String Club = "Club";
        public const String HandCrossbow = "Hand crossbow";
        public const String RepeatingCrossbow = "Repeating crossbow";
        public const String PunchingDagger = "Punching dagger";
        public const String Falchion = "Falchion";
        public const String DireFlail = "Dire flail";
        public const String HeavyFlail = "Heavy flail";
        public const String LightFlail = "Light flail";
        public const String Gauntlet = "Gauntlet";
        public const String SpikedGauntlet = "Spiked gauntlet";
        public const String Glaive = "Glaive";
        public const String Greatclub = "Greatclub";
        public const String Guisarme = "Guisarme";
        public const String Halberd = "Halberd";
        public const String Halfspear = "Halfspear";
        public const String GnomeHookedHammer = "Gnome hooked hammer";
        public const String LightHammer = "Light hammer";
        public const String Handaxe = "Handaxe";
        public const String Kukri = "Kukri";
        public const String Lance = "Lance";
        public const String Longspear = "Longspear";
        public const String Morningstar = "Morningstar";
        public const String Net = "Net";
        public const String HeavyPick = "Heavy pick";
        public const String LightPick = "Light pick";
        public const String Ranseur = "Ranseur";
        public const String Sap = "Sap";
        public const String Scythe = "Scythe";
        public const String Shuriken = "Shuriken";
        public const String Sickle = "Sickle";
        public const String TwoBladedSword = "Two-bladed sword";
        public const String Trident = "Trident";
        public const String DwarvenUrgrosh = "Dwarven urgrosh";
        public const String Warhammer = "Warhammer";
        public const String Whip = "Whip";
        public const String Arrow = "Arrow";
        public const String CrossbowBolt = "Crossbow bolt";
        public const String SlingBullet = "Sling bullet";
        public const String ThrowingAxe = "Throwing axe";
        public const String HeavyCrossbow = "Heavy crossbow";
        public const String LightCrossbow = "Light crossbow";
        public const String Dart = "Dart";
        public const String Javelin = "Javelin";
        public const String Shortbow = "Shortbow";
        public const String CompositePlus0Shortbow = "Composite (+0) shortbow";
        public const String CompositePlus1Shortbow = "Composite (+1) shortbow";
        public const String CompositePlus2Shortbow = "Composite (+2) shortbow";
        public const String Sling = "Sling";
        public const String Longbow = "Longbow";
        public const String CompositePlus0Longbow = "Composite (+0) longbow";
        public const String CompositePlus1Longbow = "Composite (+1) longbow";
        public const String CompositePlus2Longbow = "Composite (+2) longbow";
        public const String CompositePlus3Longbow = "Composite (+3) longbow";
        public const String CompositePlus4Longbow = "Composite (+4) longbow";
    }
}