using System;
using EquipmentGen.Common.Items;
using NUnit.Framework;

namespace EquipmentGen.Tests.Integration.Tables.Items.Magical.WondrousItems
{
    [TestFixture]
    public class WondrousItemAttributesTests : AttributesTests
    {
        protected override String tableName
        {
            get { return "WondrousItemAttributes"; }
        }

        [TestCase("Bead of force", AttributeConstants.OneTimeUse)]
        [TestCase("Bracelet of friends", AttributeConstants.OneTimeUse,
                                         AttributeConstants.Charged)]
        [TestCase("Brooch of shielding", AttributeConstants.OneTimeUse,
                                         AttributeConstants.Charged)]
        [TestCase("Candle of invocation", AttributeConstants.OneTimeUse)]
        [TestCase("Candle of truth", AttributeConstants.OneTimeUse)]
        [TestCase("Chime of opening", AttributeConstants.OneTimeUse,
                                      AttributeConstants.Charged)]
        [TestCase("Deck of illusions", AttributeConstants.OneTimeUse)]
        [TestCase("Dust of appearance", AttributeConstants.OneTimeUse)]
        [TestCase("Dust of disappearance", AttributeConstants.OneTimeUse)]
        [TestCase("Dust of illusion", AttributeConstants.OneTimeUse)]
        [TestCase("Dust of tracelessness", AttributeConstants.OneTimeUse)]
        [TestCase("Dust of dryness", AttributeConstants.OneTimeUse)]
        [TestCase("Elemental gem", AttributeConstants.OneTimeUse)]
        [TestCase("Elixer of fire breath", AttributeConstants.OneTimeUse)]
        [TestCase("Elixer of hiding", AttributeConstants.OneTimeUse)]
        [TestCase("Elixer of love", AttributeConstants.OneTimeUse)]
        [TestCase("Elixer of sneaking", AttributeConstants.OneTimeUse)]
        [TestCase("Elixer of swimming", AttributeConstants.OneTimeUse)]
        [TestCase("Elixer of truth", AttributeConstants.OneTimeUse)]
        [TestCase("Elixer of vision", AttributeConstants.OneTimeUse)]
        [TestCase("Gem of brightness", AttributeConstants.OneTimeUse,
                                       AttributeConstants.Charged)]
        [TestCase("Clay golem manual", AttributeConstants.OneTimeUse)]
        [TestCase("Flesh golem manual", AttributeConstants.OneTimeUse)]
        [TestCase("Iron golem manual", AttributeConstants.OneTimeUse)]
        [TestCase("Stone golem manual", AttributeConstants.OneTimeUse)]
        [TestCase("Greater stone golem manual", AttributeConstants.OneTimeUse)]
        [TestCase("Incense of meditation", AttributeConstants.OneTimeUse)]
        [TestCase("Keoghtom's ointment", AttributeConstants.OneTimeUse,
                                         AttributeConstants.Charged)]
        [TestCase("Manual of bodily health", AttributeConstants.OneTimeUse)]
        [TestCase("Manual of gainful exercise", AttributeConstants.OneTimeUse)]
        [TestCase("Manual of quickness in action", AttributeConstants.OneTimeUse)]
        [TestCase("Nolzur's marvelous pigments", AttributeConstants.OneTimeUse)]
        [TestCase("Necklace of fireballs type I", AttributeConstants.OneTimeUse)]
        [TestCase("Necklace of fireballs type II", AttributeConstants.OneTimeUse)]
        [TestCase("Necklace of fireballs type III", AttributeConstants.OneTimeUse)]
        [TestCase("Necklace of fireballs type IV", AttributeConstants.OneTimeUse)]
        [TestCase("Necklace of fireballs type V", AttributeConstants.OneTimeUse)]
        [TestCase("Necklace of fireballs type VI", AttributeConstants.OneTimeUse)]
        [TestCase("Necklace of fireballs type VII", AttributeConstants.OneTimeUse)]
        [TestCase("Quaal's bird feather token", AttributeConstants.OneTimeUse)]
        [TestCase("Quaal's anchor feather token", AttributeConstants.OneTimeUse)]
        [TestCase("Quaal's whip feather token", AttributeConstants.OneTimeUse)]
        [TestCase("Quaal's fan feather token", AttributeConstants.OneTimeUse)]
        [TestCase("Quaal's swan boat feather token", AttributeConstants.OneTimeUse)]
        [TestCase("Quaal's tree feather token", AttributeConstants.OneTimeUse)]
        [TestCase("Robe of useful items", AttributeConstants.OneTimeUse)]
        [TestCase("Robe of bones", AttributeConstants.OneTimeUse)]
        [TestCase("Salve of slipperiness", AttributeConstants.OneTimeUse)]
        [TestCase("Sovereign glue", AttributeConstants.OneTimeUse)]
        [TestCase("Scarab of protection", AttributeConstants.OneTimeUse,
                                          AttributeConstants.Charged)]
        [TestCase("Shrouds of disintegration", AttributeConstants.OneTimeUse)]
        [TestCase("Silversheen", AttributeConstants.OneTimeUse)]
        [TestCase("Stone salve", AttributeConstants.OneTimeUse)]
        [TestCase("Tome of clear thought", AttributeConstants.OneTimeUse)]
        [TestCase("Tome of leadership and influence", AttributeConstants.OneTimeUse)]
        [TestCase("Tome of understanding", AttributeConstants.OneTimeUse)]
        [TestCase("Unguent of timelessness", AttributeConstants.OneTimeUse)]
        [TestCase("Universal solvent", AttributeConstants.OneTimeUse)]
        [TestCase("Dimensional shackles")]
        [TestCase("Obsidian steed figurine of wondrous power")]
        [TestCase("Drums of panic")]
        [TestCase("Orange ioun stone")]
        [TestCase("Pale green prism ioun stone")]
        [TestCase("Lantern of revealing")]
        [TestCase("Robe of blending")]
        [TestCase("Amulet of proof against detection and location")]
        [TestCase("5 ft. by 10 ft. carpet of flying")]
        [TestCase("Belt of giant strength")]
        [TestCase("Vibrant purple prism ioun stone")]
        [TestCase("6th-level spell pearl of power")]
        [TestCase("Lavender and green ellipsoid ioun stone")]
        [TestCase("Ring gates")]
        [TestCase("Crystal ball")]
        [TestCase("Orb of storms")]
        [TestCase("Boots of teleportation")]
        [TestCase("7th-level spell pearl of power")]
        [TestCase("Major cloak of displacement")]
        [TestCase("Crystal ball with see invisibility")]
        [TestCase("Horn of Valhalla")]
        [TestCase("Crystal ball with detect thoughts")]
        [TestCase("6 ft. by 9 ft. carpet of flying")]
        [TestCase("Wings of flying")]
        [TestCase("Cloak of etherealness")]
        [TestCase("Daern's instant fortress")]
        [TestCase("Eyes of charming")]
        [TestCase("Robe of stars")]
        [TestCase("10 ft. by 10 ft. carpet of flying")]
        [TestCase("Darkskull")]
        [TestCase("Cube of force")]
        [TestCase("8th-level spell pearl of power")]
        [TestCase("Crystal ball with telepathy")]
        [TestCase("Greater horn of blasting")]
        [TestCase("Two spells pearl of power")]
        [TestCase("Helm of teleportation")]
        [TestCase("Gem of seeing")]
        [TestCase("Robe of the archmagi")]
        [TestCase("Mantle of faith")]
        [TestCase("Crystal ball with true seeing")]
        [TestCase("9th-level spell pearl of power")]
        [TestCase("Well of many worlds")]
        [TestCase("Apparatus of Kwalish")]
        [TestCase("Mantle of spell resistance")]
        [TestCase("Mirror of opposition")]
        [TestCase("Greater strand of prayer beads")]
        [TestCase("Amulet of mighty fists")]
        [TestCase("Eyes of petrification")]
        [TestCase("Bowl of commanding water elementals")]
        [TestCase("Brazier of commanding fire elementals")]
        [TestCase("Censer of controlling air elementals")]
        [TestCase("Stone of controlling earth elementals")]
        [TestCase("Amulet of the planes")]
        [TestCase("Robe of eyes")]
        [TestCase("Helm of brilliance")]
        [TestCase("Efreeti bottle")]
        [TestCase("Chaos diamond")]
        [TestCase("Cubic gate")]
        [TestCase("Iron flask")]
        [TestCase("Mirror of mental prowess")]
        [TestCase("Mirror of life trapping")]
        [TestCase("Boots of levitation")]
        [TestCase("Harp of charming")]
        [TestCase("Amulet of natural armor")]
        [TestCase("Hand of glory")]
        [TestCase("Deep red sphere ioun stone")]
        [TestCase("Incandescent blue sphere ioun stone")]
        [TestCase("Pale blue rhomboid ioun stone")]
        [TestCase("Pink and green sphere ioun stone")]
        [TestCase("Pink rhomboid ioun stone")]
        [TestCase("Scarlet and blue sphere ioun stone")]
        [TestCase("Decanter of endless water")]
        [TestCase("Necklace of adaptation")]
        [TestCase("3rd-level spell pearl of power")]
        [TestCase("Talisman of the sphere")]
        [TestCase("Serpentine owl figurine of wondrous power")]
        [TestCase("Lesser strand of prayer beads")]
        [TestCase("Bag of holding type IV")]
        [TestCase("Bronze griffon figurine of wondrous power")]
        [TestCase("Ebony fly figurine of wondrous power")]
        [TestCase("Glove of storing")]
        [TestCase("Dark blue rhomboid ioun stone")]
        [TestCase("Courser stone horse")]
        [TestCase("Cape of the mountebank")]
        [TestCase("Phylactery of undead turning")]
        [TestCase("Gauntlet of rust")]
        [TestCase("Boots of speed")]
        [TestCase("Goggles of night")]
        [TestCase("Medallion of thoughts")]
        [TestCase("Pipes of pain")]
        [TestCase("Boccob's blessed book")]
        [TestCase("Monk's belt")]
        [TestCase("Lyre of building")]
        [TestCase("Cloak of arachnida")]
        [TestCase("Destrier stone horse")]
        [TestCase("Belt of dwarvenkind")]
        [TestCase("Periapt of wound-closure")]
        [TestCase("Horn of the tritons")]
        [TestCase("Pearl of the sirines")]
        [TestCase("Onyx dog figurine of wondrous power")]
        [TestCase("Amulet of health")]
        [TestCase("Winged boots")]
        [TestCase("Bracers of armor")]
        [TestCase("Gloves of dexterity")]
        [TestCase("Headband of intellect")]
        [TestCase("4th-level spell pearl of power")]
        [TestCase("Periapt of wisdom")]
        [TestCase("Scabbard of keen edges")]
        [TestCase("Golden lions figurine of wondrous power")]
        [TestCase("Chime of interruption")]
        [TestCase("Broom of flying")]
        [TestCase("Marble elephant figurine of wondrous power")]
        [TestCase("Iridescent spindle ioun stone")]
        [TestCase("5 ft. by 5 ft. carpet of flying")]
        [TestCase("Horn of blasting")]
        [TestCase("Pale lavender ellipsoid ioun stone")]
        [TestCase("Pearly white spindle ioun stone")]
        [TestCase("Portable hole")]
        [TestCase("Stone of good luck (luckstone)")]
        [TestCase("Ivory goats figurine of wondrous power")]
        [TestCase("Rope of entanglement")]
        [TestCase("Mask of the skull")]
        [TestCase("Mattock of the titans")]
        [TestCase("Major circlet of blasting")]
        [TestCase("Minor cloak of displacement")]
        [TestCase("Helm of underwater action")]
        [TestCase("Greater bracers of archery")]
        [TestCase("Cloak of resistance")]
        [TestCase("Eyes of doom")]
        [TestCase("5th-level spell pearl of power")]
        [TestCase("Maul of the titans")]
        [TestCase("Strand of prayer beads")]
        [TestCase("Cloak of the bat")]
        [TestCase("Iron bands of Bilarro")]
        [TestCase("Cube of frost resistance")]
        [TestCase("Helm of telepathy")]
        [TestCase("Periapt of proof against poison")]
        [TestCase("Robe of scintillating colors")]
        [TestCase("Gray bag of tricks")]
        [TestCase("Hand of the mage")]
        [TestCase("1st-level spell pearl of power")]
        [TestCase("Phylactery of faithfulness")]
        [TestCase("Pipes of the sewers")]
        [TestCase("Goggles of minute seeing")]
        [TestCase("Hat of disguise")]
        [TestCase("Pipes of sounding")]
        [TestCase("Quiver of Ehlonna")]
        [TestCase("Heward's handy haversack")]
        [TestCase("Horn of fog")]
        [TestCase("Bag of holding type I")]
        [TestCase("Boots of elvenkind")]
        [TestCase("Boots of the winterlands")]
        [TestCase("Cloak of elvenkind")]
        [TestCase("Eyes of the eagle")]
        [TestCase("Golembane scarab")]
        [TestCase("Stone of alarm")]
        [TestCase("Rust bag of tricks")]
        [TestCase("Horseshoes of speed")]
        [TestCase("Rope of climbing")]
        [TestCase("Lens of detection")]
        [TestCase("Druid's vestments")]
        [TestCase("Silver raven figurine of wondrous power")]
        [TestCase("Cloak of charisma")]
        [TestCase("Gauntlets of ogre power")]
        [TestCase("Gloves of arrow snaring")]
        [TestCase("Clear spindle ioun stone")]
        [TestCase("2nd-level spell pearl of power")]
        [TestCase("Circlet of persuasion")]
        [TestCase("Slippers of spider climbing")]
        [TestCase("Bag of holding type II")]
        [TestCase("Lesser bracers of archery")]
        [TestCase("Dusty rose prism ioun stone")]
        [TestCase("Helm of comprehend languages and read magic")]
        [TestCase("Vest of escape")]
        [TestCase("Eversmoking bottle")]
        [TestCase("Murlynd's spoon")]
        [TestCase("Boots of striding and springing")]
        [TestCase("Wind fan")]
        [TestCase("Horseshoes of a zephyr")]
        [TestCase("Pipes of haunting")]
        [TestCase("Gloves of swimming and climbing")]
        [TestCase("Tan bag of tricks")]
        [TestCase("Minor circlet of blasting")]
        [TestCase("Horn of goodness/evil")]
        [TestCase("Folding boat")]
        [TestCase("Cloak of the manta ray")]
        [TestCase("Bottle of air")]
        [TestCase("Bag of holding type III")]
        [TestCase("Periapt of health")]
        public override void Attributes(String name, params String[] attributes)
        {
            base.Attributes(name, attributes);
        }
    }
}