using NUnit.Framework;
using TreasureGen.Tables;
using TreasureGen.Items;

namespace TreasureGen.Tests.Integration.Tables.Items.Magical.Weapons.Specific
{
    [TestFixture]
    public class SpecificWeaponsAttributesTests : CollectionsTests
    {
        protected override string tableName
        {
            get { return string.Format(TableNameConstants.Collections.Formattable.SpecificITEMTYPEAttributes, ItemTypeConstants.Weapon); }
        }

        [TestCase(WeaponConstants.SleepArrow,
            AttributeConstants.Ammunition,
            AttributeConstants.Specific,
            AttributeConstants.Ranged,
            AttributeConstants.Wood,
            AttributeConstants.Metal)]
        [TestCase(WeaponConstants.ScreamingBolt,
            AttributeConstants.Ammunition,
            AttributeConstants.Specific,
            AttributeConstants.Ranged,
            AttributeConstants.Metal)]
        [TestCase(WeaponConstants.SilverDagger,
            AttributeConstants.Specific,
            AttributeConstants.Melee,
            AttributeConstants.Metal)]
        [TestCase(WeaponConstants.Longsword,
            AttributeConstants.Melee,
            AttributeConstants.Specific,
            AttributeConstants.Metal)]
        [TestCase(WeaponConstants.JavelinOfLightning,
            AttributeConstants.Specific,
            AttributeConstants.Ranged,
            AttributeConstants.Wood,
            AttributeConstants.Metal,
            AttributeConstants.Thrown,
            AttributeConstants.OneTimeUse)]
        [TestCase(WeaponConstants.SlayingArrow,
            AttributeConstants.Ammunition,
            AttributeConstants.Specific,
            AttributeConstants.Ranged,
            AttributeConstants.Wood,
            AttributeConstants.Metal)]
        [TestCase(WeaponConstants.Dagger,
            AttributeConstants.Specific,
            AttributeConstants.Melee,
            AttributeConstants.Metal)]
        [TestCase(WeaponConstants.Battleaxe,
            AttributeConstants.Specific,
            AttributeConstants.Melee,
            AttributeConstants.Metal)]
        [TestCase(WeaponConstants.GreaterSlayingArrow,
            AttributeConstants.Ammunition,
            AttributeConstants.Specific,
            AttributeConstants.Ranged,
            AttributeConstants.Wood,
            AttributeConstants.Metal)]
        [TestCase(WeaponConstants.Shatterspike,
            AttributeConstants.Specific,
            AttributeConstants.Melee,
            AttributeConstants.Metal)]
        [TestCase(WeaponConstants.DaggerOfVenom,
            AttributeConstants.Specific,
            AttributeConstants.Melee,
            AttributeConstants.Metal)]
        [TestCase(WeaponConstants.TridentOfWarning,
            AttributeConstants.Specific,
            AttributeConstants.Melee,
            AttributeConstants.Metal)]
        [TestCase(WeaponConstants.AssassinsDagger,
            AttributeConstants.Specific,
            AttributeConstants.Melee,
            AttributeConstants.Metal)]
        [TestCase(WeaponConstants.ShiftersSorrow,
            AttributeConstants.Specific,
            AttributeConstants.Melee,
            AttributeConstants.DoubleWeapon,
            AttributeConstants.Metal,
            AttributeConstants.TwoHanded)]
        [TestCase(WeaponConstants.TridentOfFishCommand,
            AttributeConstants.Specific,
            AttributeConstants.Melee,
            AttributeConstants.Metal)]
        [TestCase(WeaponConstants.FlameTongue,
            AttributeConstants.Specific,
            AttributeConstants.Melee,
            AttributeConstants.Metal)]
        [TestCase(WeaponConstants.LuckBlade0,
            AttributeConstants.Specific,
            AttributeConstants.Melee,
            AttributeConstants.Metal,
            AttributeConstants.Charged)]
        [TestCase(WeaponConstants.LuckBlade,
            AttributeConstants.Specific,
            AttributeConstants.Melee,
            AttributeConstants.Metal,
            AttributeConstants.Charged)]
        [TestCase(WeaponConstants.SwordOfSubtlety,
            AttributeConstants.Specific,
            AttributeConstants.Melee,
            AttributeConstants.Metal)]
        [TestCase(WeaponConstants.SwordOfThePlanes,
            AttributeConstants.Specific,
            AttributeConstants.Melee,
            AttributeConstants.Metal)]
        [TestCase(WeaponConstants.NineLivesStealer,
            AttributeConstants.Specific,
            AttributeConstants.Melee,
            AttributeConstants.Metal)]
        [TestCase(WeaponConstants.SwordOfLifeStealing,
            AttributeConstants.Specific,
            AttributeConstants.Melee,
            AttributeConstants.Metal)]
        [TestCase(WeaponConstants.Oathbow,
            AttributeConstants.Specific,
            AttributeConstants.Ranged,
            AttributeConstants.Wood,
            AttributeConstants.TwoHanded)]
        [TestCase(WeaponConstants.MaceOfTerror,
            AttributeConstants.Specific,
            AttributeConstants.Melee,
            AttributeConstants.Metal)]
        [TestCase(WeaponConstants.LifeDrinker,
            AttributeConstants.Specific,
            AttributeConstants.Melee,
            AttributeConstants.Metal,
            AttributeConstants.TwoHanded)]
        [TestCase(WeaponConstants.SylvanScimitar,
            AttributeConstants.Specific,
            AttributeConstants.Melee,
            AttributeConstants.Metal)]
        [TestCase(WeaponConstants.RapierOfPuncturing,
            AttributeConstants.Specific,
            AttributeConstants.Melee,
            AttributeConstants.Metal)]
        [TestCase(WeaponConstants.SunBlade,
            AttributeConstants.Specific,
            AttributeConstants.Melee,
            AttributeConstants.Metal)]
        [TestCase(WeaponConstants.FrostBrand,
            AttributeConstants.Specific,
            AttributeConstants.Melee,
            AttributeConstants.Metal,
            AttributeConstants.TwoHanded)]
        [TestCase(WeaponConstants.DwarvenThrower,
            AttributeConstants.Specific,
            AttributeConstants.Melee,
            AttributeConstants.Metal)]
        [TestCase(WeaponConstants.LuckBlade1,
            AttributeConstants.Specific,
            AttributeConstants.Melee,
            AttributeConstants.Metal,
            AttributeConstants.Charged)]
        [TestCase(WeaponConstants.MaceOfSmiting,
            AttributeConstants.Specific,
            AttributeConstants.Melee,
            AttributeConstants.Metal)]
        [TestCase(WeaponConstants.LuckBlade2,
            AttributeConstants.Specific,
            AttributeConstants.Melee,
            AttributeConstants.Metal,
            AttributeConstants.Charged)]
        [TestCase(WeaponConstants.HolyAvenger,
            AttributeConstants.Specific,
            AttributeConstants.Melee,
            AttributeConstants.Metal)]
        [TestCase(WeaponConstants.LuckBlade3,
            AttributeConstants.Specific,
            AttributeConstants.Melee,
            AttributeConstants.Metal,
            AttributeConstants.Charged)]
        [TestCase(WeaponConstants.CursedMinus2Sword,
            AttributeConstants.Specific,
            AttributeConstants.Melee,
            AttributeConstants.Metal)]
        [TestCase(WeaponConstants.CursedBackbiterSpear,
            AttributeConstants.Specific,
            AttributeConstants.Melee,
            AttributeConstants.Metal,
            AttributeConstants.Wood,
            AttributeConstants.Ranged,
            AttributeConstants.Thrown)]
        [TestCase(WeaponConstants.NetOfSnaring,
            AttributeConstants.Specific,
            AttributeConstants.Ranged,
            AttributeConstants.Thrown,
            AttributeConstants.TwoHanded)]
        [TestCase(WeaponConstants.MaceOfBlood,
            AttributeConstants.Specific,
            AttributeConstants.Melee)]
        [TestCase(WeaponConstants.BerserkingSword,
            AttributeConstants.Specific,
            AttributeConstants.Melee,
            AttributeConstants.Metal,
            AttributeConstants.TwoHanded)]
        public void SpecificWeaponAttributes(string name, params string[] attributes)
        {
            base.Collections(name, attributes);
        }

        [TestCase(WeaponConstants.BerserkingSword)]
        [TestCase(WeaponConstants.MaceOfBlood)]
        [TestCase(WeaponConstants.NetOfSnaring)]
        [TestCase(WeaponConstants.CursedBackbiterSpear)]
        [TestCase(WeaponConstants.CursedMinus2Sword)]
        public void SpecificCursedWeaponMatchesAttributes(string item)
        {
            var specificCursedAttributes = CollectionMapper.Map(TableNameConstants.Collections.Set.SpecificCursedItemAttributes);
            var specificAttributes = GetCollection(item);

            Assert.That(specificAttributes, Is.EquivalentTo(specificCursedAttributes[item]));
        }
    }
}