using System;

namespace EquipmentGen.Common.Items
{
    public static class SpecialAbilityConstants
    {
        public const String Glamered = "Glamered";
        public const String LightFortification = "Light fortification";
        public const String Fortification = "Fortification";
        public const String ModerateFortification = "Moderate fortification";
        public const String HeavyFortification = "Heavy fortification";
        public const String Slick = "Slick";
        public const String Shadow = "Shadow";
        public const String SilentMoves = "Silent moves";
        public const String ImprovedSlick = "Improved slick";
        public const String ImprovedShadow = "Improved shadow";
        public const String ImprovedSilentMoves = "Improved silent moves";
        public const String GreaterSlick = "Greater slick";
        public const String GreaterShadow = "Greater shadow";
        public const String GreaterSilentMoves = "Greater silent moves";
        public const String SpellResistance = "Spell resistance";
        public const String SpellResistance13 = "Spell resistance (13)";
        public const String SpellResistance15 = "Spell resistance (15)";
        public const String SpellResistance17 = "Spell resistance (17)";
        public const String SpellResistance19 = "Spell resistance (19)";
        public const String AcidResistance = "Acid resistance";
        public const String ColdResistance = "Cold resistance";
        public const String ElectricityResistance = "Electricity resistance";
        public const String FireResistance = "Fire resistance";
        public const String SonicResistance = "Sonic resistance";
        public const String ImprovedAcidResistance = "Improved acid resistance";
        public const String ImprovedColdResistance = "Improved cold resistance";
        public const String ImprovedElectricityResistance = "Improved electricity resistance";
        public const String ImprovedFireResistance = "Improved fire resistance";
        public const String ImprovedSonicResistance = "Improved sonic resistance";
        public const String GreaterAcidResistance = "Greater acid resistance";
        public const String GreaterColdResistance = "Greater cold resistance";
        public const String GreaterElectricityResistance = "Greater electricity resistance";
        public const String GreaterFireResistance = "Greater fire resistance";
        public const String GreaterSonicResistance = "Greater sonic resistance";
        public const String GhostTouch = "Ghost touch";
        public const String GhostTouchWeapon = "Ghost touch (weapon)";
        public const String GhostTouchArmor = "Ghost touch (armor)";
        public const String Invulnerability = "Invulnerability";
        public const String Wild = "Wild";
        public const String Etherealness = "Etherealness";
        public const String UndeadControlling = "Undead controlling";
        public const String ArrowCatching = "Arrow catching";
        public const String ArrowDeflection = "Arrow deflection";
        public const String Bashing = "Bashing";
        public const String Blinding = "Blinding";
        public const String Animated = "Animated";
        public const String Bane = "Bane";
        public const String Reflecting = "Reflecting";
        public const String Distance = "Distance";
        public const String Flaming = "Flaming";
        public const String Frost = "Frost";
        public const String Shock = "Shock";
        public const String Merciful = "Merciful";
        public const String Returning = "Returning";
        public const String Seeking = "Seeking";
        public const String Thundering = "Thundering";
        public const String Anarchic = "Anarchic";
        public const String Axiomatic = "Axiomatic";
        public const String Disruption = "Disruption";
        public const String FlamingBurst = "Flaming burst";
        public const String IcyBurst = "Icy burst";
        public const String ShockingBurst = "Shocking burst";
        public const String Holy = "Holy";
        public const String Unholy = "Unholy";
        public const String Wounding = "Wounding";
        public const String Speed = "Speed";
        public const String Dancing = "Dancing";
        public const String Vorpal = "Vorpal";
        public const String BrilliantEnergy = "Brilliant energy";
        public const String Defending = "Defending";
        public const String Keen = "Keen";
        public const String KiFocus = "Ki focus";
        public const String MightyCleaving = "Mighty cleaving";
        public const String SpellStoring = "Spell storing";
        public const String Vicious = "Vicious";
        public const String Throwing = "Throwing";
    }
}